node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Connection lost: The server closed the connection.
    at Protocol.end (D:\projects\rms\abay-rms\backend\backend_api\node_modules\mysql\lib\protocol\Protocol.js:112:13)
    at Socket.<anonymous> (D:\projects\rms\abay-rms\backend\backend_api\node_modules\mysql\lib\Connection.js:94:28)
    at Socket.<anonymous> (D:\projects\rms\abay-rms\backend\backend_api\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (D:\projects\rms\abay-rms\backend\backend_api\node_modules\mysql\lib\Connection.js:423:8)
    at Protocol.emit (node:events:513:28)
    at Protocol._delegateError (D:\projects\rms\abay-rms\backend\backend_api\node_modules\mysql\lib\protocol\Protocol.js:398:10)
    at Protocol.end (D:\projects\rms\abay-rms\backend\backend_api\node_modules\mysql\lib\protocol\Protocol.js:116:8)
    at Socket.<anonymous> (D:\projects\rms\abay-rms\backend\backend_api\node_modules\mysql\lib\Connection.js:94:28)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  fatal: true,
  code: 'PROTOCOL_CONNECTION_LOST'
}
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
Retrying
